hello:
    path: /hello/{prenom}
    controller: App\Controller\HelloWorldControler::hello
    requirements:
        prenom: '[a-zA-Z]+'
form:
    path: /form
    controller: App\Controller\HelloWorldControler::form
    methods: GET
formReceive:
    path: /form
    controller: App\Controller\HelloWorldControler::formReceive
    methods: POST
liste:
    path: /liste
    controller: App\Controller\HelloWorldControler::liste
loginForm:
    path: /login
    controller: App\Controller\LoginController::loginForm
    methods: GET | POST
userForm:
    path: /user/create
    controller: App\Controller\UserController::create
    methods: GET | POST
